### ISSUE TITLE
How can you use it ??

### ISSUE THREAD

**Issue by Systemac** [henriquemiranda/degiropy#1]
Thank's for you job 

I have an issue :

Traceback (most recent call last):
  File "degiro", line 26, in <module>
    s = Session.login()
  File "C:[...]\site-packages\degiropy-0.1-py3.7.egg\degiropy\session.py", line 24, in login
  File "C:[...]\site-packages\degiropy-0.1-py3.7.egg\degiropy\session.py", line 12, in __init__
  File "C:[...]\site-packages\degiropy-0.1-py3.7.egg\degiropy\session.py", line 29, in get_account_id
KeyError: 'intAccount'

**Comment by Systemac** [comment]
I just look the post method, This is the name of the variable, yet I installed the package with the credentials ....

**Comment by Systemac** [comment]
session.py modified, closed.
